Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,67 +1,65 @@
-# This workflow uses actions that are not certified by GitHub.
-# They are provided by a third-party and are governed by
-# separate terms of service, privacy policy, and support
-# documentation. The..
-
 name: Deploy Jekyll site to Pages
 
 on:
-    push:
-        branches: ["main"]
+push:
+branches: ["main"]
 
 concurrency:
-    group: "pages"
-    cancel-in-progress: false
+group: "pages"
+cancel-in-progress: false
 
 permissions:
-    contents: read
-    pages: write
-    id-token: write
+contents: read
+pages: write
+id-token: write
 
 jobs:
-    # Build job
-    build:
-        runs-on: ubuntu-latest
-        steps:
-            - name: Checkout
-              uses: actions/checkout@v4
-            - name: Setup Ruby
-              uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
-              with:
-                  ruby-version: "3.1" # Not needed with a .ruby-version file
-                  bundler-cache: true # runs 'bundle install' and caches installed gems automatically
-                  cache-version: 0 # Increment this number if you need to re-download cached gems
-            - name: Install dependencies 
-              run:  bundle install
-            - name: Setup Pages
-              id: pages
-              uses: actions/configure-pages@v3
-            - name: Build with Jekyll
-              run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
-            - name: Copy CNAME file
-              run: cp CNAME _site/
-              env:
-                  JEKYLL_ENV: production
-            - name: Upload artifact
-              uses: actions/upload-artifact@v3
-              with:
-                name: github-pages
-                path: _site
-                retention-days: 1
-            - name: Upload artifact
-              uses: actions/upload-pages-artifact@v3
-              with:
-                  path: _site
+# Build job
+build:
+runs-on: ubuntu-latest
+steps:
+- name: Checkout
+uses: actions/checkout@v4
+
+- name: Setup Ruby
+uses: ruby/setup-ruby@v1
+with:
+ruby-version: "3.1"
+bundler-cache: true
+cache-version: 0
+
+- name: Update Bundler
+run: gem install bundler
+
+- name: Clean Cache
+run: rm -rf vendor/bundle || true
+
+- name: Install dependencies
+run: bundle install
+
+- name: Setup Pages
+id: pages
+uses: actions/configure-pages@v3
+
+- name: Build with Jekyll
+run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
+env:
+JEKYLL_ENV: production
+
+- name: Copy CNAME file
+run: cp CNAME _site/ || echo "CNAME file not found, skipping"
+
+- name: Upload artifact
+uses: actions/upload-artifact@v4
+with:
+name: github-pages
+          path: _site
+          path: |
+            _site/**
+            !_site/assets/js/bootstrap.min.js.map:Zone.Identifier
+         retention-days: 1
 
 
-    # Deployment job
-    deploy:
-        environment:
-            name: github-pages
-            url: ${{ steps.deployment.outputs.page_url }}
-        runs-on: ubuntu-22.04
-        needs: build
-        steps:
-            - name: Deploy to GitHub Pages
-              id: deployment
-              uses: actions/deploy-pages@v4
+# Deployment job
+deploy:
+environment:
